# Generated by Django 3.1.4 on 2021-01-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
